name: Benchmark Pipeline
on:
  push:
    branches: [ main ]
jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy

    - name: Change Directory
      run: cd 'With DB Speed Records'

    - name: Run benchmark BFMS script
      run: |
        python Hybrid_BFMS.py  

    - name: Run benchmark TFMS script
      run: |
        python Hybrid_TFMS.py

    - name: Run benchmark BF script
      run: |
        python HybridBF.py

    - name: Run benchmark TF script
      run: |
        python HybridTF.py  

    - name: Debug Results.db
      run: |
        ls -l

    - name: Upload results database
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: 'With DB Speed Records/Results.db'