name: Benchmark Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy

    - name: Run benchmark scripts
      working-directory: ./With DB Speed Records
      run: |
        python Hybrid_BFMS.py
        python Hybrid_TFMS.py
        python HybridBF.py
        python HybridTF.py

    - name: Verify results file
      run: |
        ls -lh "./With DB Speed Records/Results.db"
        file "./With DB Speed Records/Results.db"

    - name: Upload results database
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: ./With DB Speed Records/Results.db