name: Benchmark Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clean previous results
      run: rm -f Results.db

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy

    - name: Run BF scripts
      run: |
        python Old_BF.py
        python Optimized_BF.py

    - name: Run TF scripts
      run: |
        python Old_TF.py
        python Optimized_TF.py
        
    - name: Run TFMS scripts
      run: |
        python Old_TFMS.py
        python Optimized_TFMS.py

    - name: Run BFMS scripts
      run: |
        python Old_BFMS.py
        python Optimized_BFMS.py

    - name: Verify results file
      run: |
        ls -l 

    - name: Upload results database
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: ./Results.db