name: Benchmark Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clean previous results
      run: rm -f Results.db

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy numpy pandas

    - name: Run Python scripts
      run: |
        for script in $(ls [0-9][0-9]-*.py); do
          echo "Running $script..."
          python "$script"
          if [ $? -ne 0 ]; then
            echo "Error running $script"
            exit 1
          fi
        done

    - name: Verify results file
      run: |
        if [ ! -f Results.db ]; then
          echo "Results.db was not created!"
          exit 1
        fi
        ls -l Results.db
        file_size=$(stat -f%z Results.db || stat -c%s Results.db)
        if [ "$file_size" -eq 0 ]; then
          echo "Results.db is empty!"
          exit 1
        fi
        echo "Results.db size: $file_size bytes"

    - name: Upload results database
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: ./Results.db